# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - pip install bigrest sphinx sphinx_rtd_theme
    - make -C docs html
    - mkdir --parents _readthedocs/html/
    - cp --recursive docs/build/html/* _readthedocs/html/

#sphinx:
#  configuration: docs/source/conf.py
#  fail_on_warning: true